### ISSUE TITLE
AttributeError: module 'resreg' has no attribute 'sigmoid_relevance'

### ISSUE THREAD

**Issue by cesarteaser** [jafetgado/resreg#2]
Hi,
I am trying to call the sigmoid_relevance function as per tutorial but it throws me an error and I cannot find any solutions online. I hope you can help:

```
#!git clone https://github.com/jafetgado/resreg.git
#!cd resreg
#!pip install -e resreg
import resreg
relevance = resreg.sigmoid_relevance(y, cl=None, ch=np.percentile(y, 90))

AttributeError                            Traceback (most recent call last)
<ipython-input-28-eb94965e6230> in <module>
      2 
      3 # Resample training set with random oversampling
----> 4 relevance = resreg.sigmoid_relevance(y, cl=None, ch=np.percentile(y, 90))

AttributeError: module 'resreg' has no attribute 'sigmoid_relevance'
```

**Comment by jafetgado** [comment]
This is strange. 
Did you do a `pip install` or `git clone`?
What is the output you get if you run

```Python
import resreg
print(resreg.__file__)
```

**Comment by cesarteaser** [comment]
Hi, when I run 
import resreg
print(resreg.__file__), I get 'NONE'. I did both, pip install and git clone. What else do you recommend checking on my end?

**Comment by jafetgado** [comment]
This error was due to the classic mistake of forgetting to include a `__init__.py` file in the package.
I have corrected this error.

Please, go ahead and re-install `resreg`, with `git clone...; python setup.py install`. It should work fine now.

**Comment by cesarteaser** [comment]
Thank you for looking into it. I uninstalled resreg using !pip uninstall resreg. Then, I am runing these lines and I still get the same error:
```
!git clone https://github.com/jafetgado/resreg.git
!cd resreg
!pip install resreg
```
What am I missing?

**Comment by jafetgado** [comment]
Are you doing this on your machine, or on a virtual machine like Google Colab? If you're using Google Colab, ensure that you restart/reset the runtime before installing the new version. And, `!pip install resreg` should work fine now.

**Comment by cesarteaser** [comment]
Perfect, it runs now! Thanks a ton and super cool and rare library!
